#!/bin/bash

echo "🎉 HostelConnect - How to Use the App"
echo "===================================="
echo ""

echo -e "\033[0;32m✅ API Status: Running on http://localhost:3000\033[0m"
echo ""

echo -e "\033[1;33m📱 Step 1: Start the Flutter App\033[0m"
echo "Open a new terminal and run:"
echo "cd hostelconnect/mobile"
echo "flutter run lib/main_responsive.dart"
echo ""

echo -e "\033[0;34m🎯 Step 2: Test the App Features\033[0m"
echo ""

echo -e "\033[1;32m1. Role Switching:\033[0m"
echo "• Tap the profile icon (top right)"
echo "• Select different roles: Student, Warden, Warden Head, Super Admin, Chef"
echo "• Each role shows different dashboard content"
echo ""

echo -e "\033[1;32m2. Navigation:\033[0m"
echo "• Phones: Use bottom navigation bar"
echo "• Tablets/Desktop: Use left navigation rail"
echo "• Resize window to see responsive breakpoints"
echo ""

echo -e "\033[1;32m3. Gate Pass (with Ads):\033[0m"
echo "• Tap 'Gate Pass' in navigation"
echo "• Fill out the form"
echo "• Tap 'Watch Ad & Submit'"
echo "• Watch the 20-second interstitial ad"
echo "• Ad unlocks the submit button"
echo ""

echo -e "\033[1;32m4. Attendance Scanner:\033[0m"
echo "• Tap 'Scan' in navigation"
echo "• Toggle kiosk mode (desktop icon)"
echo "• In kiosk mode: landscape orientation, two-pane layout"
echo "• Tap 'Simulate Scan' to test QR scanning"
echo ""

echo -e "\033[1;32m5. Meals Management:\033[0m"
echo "• Tap 'Meals' in navigation"
echo "• Set meal preferences with toggle switches"
echo "• Use quick action chips (All Yes, All No, Same as Yesterday)"
echo "• Responsive layout: vertical on phones, grid on tablets"
echo ""

echo -e "\033[1;32m6. Responsive Design:\033[0m"
echo "• Resize the app window to test breakpoints:"
echo "  - xs < 360px: Single column, compact"
echo "  - sm 360-479px: Single column, standard"
echo "  - md 480-839px: Two columns"
echo "  - lg 840-1199px: Three columns, NavigationRail"
echo "  - xl ≥ 1200px: Four columns, desktop layout"
echo ""

echo -e "\033[0;34m🔧 Step 3: Test API Endpoints\033[0m"
echo "Run this command to test all API features:"
echo "cd hostelconnect && ./test-api.sh"
echo ""

echo -e "\033[0;34m📊 What Each Role Shows:\033[0m"
echo ""

echo -e "\033[1;33mStudent Dashboard:\033[0m"
echo "• Welcome message with room info"
echo "• Quick action chips (Gate Pass, Meals, Complaints, Profile)"
echo "• Live metrics: Gate Pass Status, Meals Today, Attendance"
echo "• Recent activity feed"
echo ""

echo -e "\033[1;33mWarden Dashboard:\033[0m"
echo "• Block statistics (Students, Present, Absent)"
echo "• Quick actions (Start Attendance, Gate Passes, Complaints, Reports)"
echo "• Live metrics: Attendance Rate, Pending Gate Passes, Active Complaints"
echo "• Recent activity feed"
echo ""

echo -e "\033[1;33mOther Roles:\033[0m"
echo "• Warden Head: Multi-block overview"
echo "• Super Admin: System-wide analytics"
echo "• Chef: Meal planning and forecasting"
echo ""

echo -e "\033[0;34m🎮 Interactive Features:\033[0m"
echo "• Touch-friendly 44px minimum touch targets"
echo "• Haptic feedback on interactions"
echo "• Material 3 design with consistent spacing"
echo "• Smooth animations and transitions"
echo "• Accessibility compliant"
echo ""

echo -e "\033[0;34m🔗 API Endpoints Available:\033[0m"
echo "• GET  / - API status"
echo "• POST /auth/login - Authentication"
echo "• POST /gate-pass - Create gate pass"
echo "• GET  /dash/hostel-live - Live dashboard"
echo "• GET  /ads/eligible - Ad eligibility"
echo "• POST /ads/event - Ad tracking"
echo "• POST /attendance/sessions - Start attendance"
echo "• POST /meals/intents/open - Open meal intents"
echo ""

echo -e "\033[1;32m🚀 Ready to Test!\033[0m"
echo ""
echo -e "\033[0;34mThe app is fully functional with:\033[0m"
echo "• Real screens with actual content"
echo "• Responsive design for all devices"
echo "• Working API backend"
echo "• Ad system with interstitial ads"
echo "• QR scanning with kiosk mode"
echo "• Role-based navigation"
echo "• Live dashboard metrics"
echo ""
echo -e "\033[1;33mStart the Flutter app and explore! 🎉\033[0m"
