#!/usr/bin/env bash

echo "🎉 Android Studio Setup Guide"
echo "============================="
echo ""
echo "Android Studio has been installed! Here's what to do next:"
echo ""
echo "1. 🚀 Launch Android Studio:"
echo "   - Open Applications folder"
echo "   - Double-click 'Android Studio.app'"
echo "   - OR run: open -a 'Android Studio'"
echo ""
echo "2. 📱 First-time setup:"
echo "   - Choose 'Standard' installation"
echo "   - Let it download Android SDK components"
echo "   - Accept all licenses when prompted"
echo ""
echo "3. 🧪 Create an emulator:"
echo "   - Go to Tools → AVD Manager"
echo "   - Click 'Create Virtual Device'"
echo "   - Choose 'Pixel 7'"
echo "   - Select 'API 34 (Android 14)' system image"
echo "   - Click 'Finish'"
echo ""
echo "4. ▶️  Start the emulator:"
echo "   - Click the ▶️  button next to your AVD"
echo "   - Wait for it to boot up"
echo ""
echo "5. 🏃‍♂️ Run HostelConnect:"
echo "   - Open terminal"
echo "   - Run: cd mobile && flutter run"
echo ""
echo "Let me launch Android Studio for you..."

# Launch Android Studio
open -a "Android Studio"

echo ""
echo "✅ Android Studio is launching!"
echo "Follow the steps above to complete the setup."
echo ""
echo "Once you have an emulator running, you can test HostelConnect with:"
echo "cd mobile && flutter run"
