name: hostelconnect
description: HostelConnect - Working hostel management system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^12.1.3
  
  # UI Components
  cupertino_icons: ^1.0.6
  
  # Networking & Storage
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  
  # QR Scanner (ENABLED for education pipeline)
  mobile_scanner: ^5.1.0
  
  # Background Sync (Commented out - causing build issues)
  # workmanager: ^0.5.2
  
  # Firebase (if using Firebase - add when ready)
  # firebase_core: ^2.24.0
  # firebase_auth: ^4.15.0
  # firebase_firestore: ^4.13.0
  # firebase_storage: ^11.5.0
  # firebase_messaging: ^14.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
