name: Codespaces Prebuilds

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Validate devcontainer.json
        uses: devcontainers/ci@v0.3
        with:
          runCmd: echo "✅ Codespace environment validated successfully!"
